create extension if not exists pgcrypto with schema extensions;

create type public.app_scope_type as enum ('system', 'company', 'event', 'self');
create type public.company_status as enum ('draft', 'active', 'inactive', 'suspended', 'archived');
create type public.subscription_status as enum ('trialing', 'active', 'past_due', 'cancelled', 'expired');
create type public.user_status as enum ('pending_invite', 'active', 'inactive', 'suspended');
create type public.membership_status as enum ('invited', 'active', 'suspended', 'revoked');
create type public.event_status as enum ('draft', 'published', 'active', 'completed', 'archived');
create type public.event_visibility as enum ('private', 'unlisted', 'public');
create type public.asset_kind as enum ('image', 'video', 'audio', 'document', 'font', 'other');
create type public.asset_visibility as enum ('private', 'company', 'event', 'public');
create type public.custom_field_kind as enum (
    'text',
    'textarea',
    'email',
    'phone',
    'number',
    'select',
    'multiselect',
    'radio',
    'checkbox',
    'date',
    'datetime',
    'file',
    'qr',
    'barcode',
    'boolean'
);
create type public.custom_field_target as enum ('registration', 'checkin', 'landing_page', 'internal');
create type public.client_status as enum ('pending', 'registered', 'confirmed', 'checked_in', 'cancelled', 'blocked');
create type public.client_source as enum ('manual', 'import', 'landing_page', 'api', 'sync');
create type public.checkin_status as enum ('checked_in', 'checked_out', 'reverted');
create type public.checkin_method as enum ('qr', 'search', 'manual', 'offline_sync', 'api');
create type public.report_kind as enum ('table', 'metric', 'chart', 'export', 'dashboard');
create type public.report_run_status as enum ('queued', 'running', 'success', 'failed', 'cancelled');
create type public.content_publication_status as enum ('draft', 'published', 'archived');
create type public.landing_page_submission_status as enum ('submitted', 'confirmed', 'rejected', 'synced');
create type public.campaign_status as enum ('draft', 'scheduled', 'sending', 'sent', 'paused', 'cancelled', 'failed');
create type public.campaign_recipient_status as enum (
    'pending',
    'queued',
    'sent',
    'delivered',
    'opened',
    'clicked',
    'bounced',
    'failed',
    'cancelled'
);
create type public.email_sender_status as enum ('active', 'inactive', 'pending_verification', 'error');
create type public.print_job_kind as enum ('label', 'card', 'badge', 'document');
create type public.print_job_status as enum ('queued', 'processing', 'completed', 'failed', 'cancelled');
create type public.print_item_status as enum ('queued', 'rendered', 'printed', 'failed', 'cancelled');
create type public.printer_status as enum ('active', 'inactive', 'error');
create type public.lucky_draw_status as enum ('draft', 'ready', 'running', 'paused', 'completed', 'archived');
create type public.lucky_draw_entry_status as enum ('eligible', 'ineligible', 'won', 'removed');
create type public.chat_session_status as enum ('open', 'closed', 'archived');
create type public.chatbot_message_role as enum ('system', 'assistant', 'user', 'tool');
create type public.integration_provider as enum ('postmark', 'n8n', 'print_bridge', 'storage', 'webhook', 'other');
create type public.integration_status as enum ('active', 'inactive', 'error');
create type public.integration_log_status as enum ('success', 'warning', 'error', 'info');
create type public.background_job_kind as enum (
    'import_clients',
    'export_clients',
    'export_reports',
    'send_campaign',
    'generate_cards',
    'generate_labels',
    'print_batch',
    'chatbot_sync',
    'data_backfill',
    'other'
);
create type public.background_job_status as enum ('queued', 'running', 'completed', 'failed', 'cancelled');
create type public.history_actor_type as enum ('user', 'system', 'device', 'job');
create type public.system_log_level as enum ('debug', 'info', 'warn', 'error', 'fatal');
create type public.device_status as enum ('active', 'inactive', 'revoked');
create type public.sync_batch_status as enum ('queued', 'processing', 'completed', 'failed');
create type public.template_unlock_status as enum ('requested', 'approved', 'rejected', 'cancelled');

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table public.companies (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid(),
    legacy_id bigint,
    slug text not null,
    name text not null,
    legal_name text,
    status public.company_status not null default 'draft',
    timezone text not null default 'Asia/Ho_Chi_Minh',
    country_code text,
    tax_code text,
    billing_email text,
    contact_email text,
    contact_phone text,
    website_url text,
    settings jsonb not null default '{}'::jsonb,
    branding jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (public_id)
);

create unique index companies_slug_unique_idx on public.companies (lower(slug));

create table public.company_domains (
    id bigint generated by default as identity primary key,
    company_id bigint not null references public.companies(id) on delete cascade,
    domain text not null,
    is_primary boolean not null default false,
    is_active boolean not null default true,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index company_domains_domain_unique_idx on public.company_domains (lower(domain));
create unique index company_domains_primary_unique_idx on public.company_domains (company_id) where is_primary;

create table public.subscription_plans (
    id bigint generated by default as identity primary key,
    code text not null,
    name text not null,
    description text,
    billing_interval text not null default 'monthly' check (billing_interval in ('monthly', 'yearly', 'one_time', 'custom')),
    price_amount numeric(12, 2) not null default 0,
    currency_code text not null default 'USD',
    feature_flags jsonb not null default '{}'::jsonb,
    limits jsonb not null default '{}'::jsonb,
    is_active boolean not null default true,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (code)
);

create table public.company_subscriptions (
    id bigint generated by default as identity primary key,
    company_id bigint not null references public.companies(id) on delete cascade,
    plan_id bigint not null references public.subscription_plans(id) on delete restrict,
    status public.subscription_status not null default 'trialing',
    starts_at timestamptz not null default now(),
    ends_at timestamptz,
    trial_ends_at timestamptz,
    billing_metadata jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index company_subscriptions_company_status_idx on public.company_subscriptions (company_id, status);

create table public.users (
    id bigint generated by default as identity primary key,
    auth_user_id uuid references auth.users(id) on delete set null,
    legacy_id bigint,
    email text,
    full_name text,
    display_name text,
    phone text,
    avatar_url text,
    status public.user_status not null default 'pending_invite',
    login_app text not null default 'web' check (login_app in ('web', 'scanner', 'both')),
    is_super_admin boolean not null default false,
    default_company_id bigint references public.companies(id) on delete set null,
    locale text not null default 'vi',
    last_seen_at timestamptz,
    preferences jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    legacy_role_key text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (auth_user_id)
);

create unique index users_email_unique_idx on public.users (lower(email)) where email is not null;
create index users_default_company_idx on public.users (default_company_id);

create table public.roles (
    id bigint generated by default as identity primary key,
    key text not null,
    name text not null,
    description text,
    default_scope public.app_scope_type not null default 'company',
    is_system_role boolean not null default false,
    is_active boolean not null default true,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (key)
);

create table public.permissions (
    id bigint generated by default as identity primary key,
    key text not null,
    resource text not null,
    action text not null,
    description text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (key)
);

create table public.role_permissions (
    role_id bigint not null references public.roles(id) on delete cascade,
    permission_id bigint not null references public.permissions(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (role_id, permission_id)
);

create table public.events (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid(),
    legacy_id bigint,
    company_id bigint not null references public.companies(id) on delete cascade,
    slug text not null,
    code text,
    name text not null,
    description text,
    timezone text not null default 'Asia/Ho_Chi_Minh',
    location_name text,
    location_address text,
    starts_at timestamptz,
    ends_at timestamptz,
    registration_opens_at timestamptz,
    registration_closes_at timestamptz,
    status public.event_status not null default 'draft',
    visibility public.event_visibility not null default 'private',
    feature_flags jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (public_id)
);

create unique index events_company_slug_unique_idx on public.events (company_id, lower(slug));
create unique index events_company_code_unique_idx on public.events (company_id, lower(code)) where code is not null;
create index events_company_status_idx on public.events (company_id, status);

create table public.user_access_scopes (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    role_id bigint not null references public.roles(id) on delete cascade,
    scope_type public.app_scope_type not null,
    company_id bigint references public.companies(id) on delete cascade,
    event_id bigint references public.events(id) on delete cascade,
    membership_status public.membership_status not null default 'active',
    granted_by_user_id bigint references public.users(id) on delete set null,
    starts_at timestamptz,
    ends_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (
        (scope_type = 'system' and company_id is null and event_id is null)
        or (scope_type = 'company' and company_id is not null and event_id is null)
        or (scope_type = 'event' and company_id is not null and event_id is not null)
        or (scope_type = 'self' and company_id is null and event_id is null)
    )
);

create unique index user_access_scopes_unique_idx
    on public.user_access_scopes (
        user_id,
        role_id,
        scope_type,
        coalesce(company_id, 0),
        coalesce(event_id, 0)
    );
create index user_access_scopes_user_idx on public.user_access_scopes (user_id, membership_status);
create index user_access_scopes_company_idx on public.user_access_scopes (company_id, membership_status);
create index user_access_scopes_event_idx on public.user_access_scopes (event_id, membership_status);

create table public.event_settings (
    id bigint generated by default as identity primary key,
    event_id bigint not null references public.events(id) on delete cascade,
    legacy_id bigint,
    registration_settings jsonb not null default '{}'::jsonb,
    checkin_settings jsonb not null default '{}'::jsonb,
    report_settings jsonb not null default '{}'::jsonb,
    print_settings jsonb not null default '{}'::jsonb,
    communication_settings jsonb not null default '{}'::jsonb,
    public_settings jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (event_id)
);

create table public.event_areas (
    id bigint generated by default as identity primary key,
    event_id bigint not null references public.events(id) on delete cascade,
    legacy_id bigint,
    code text not null,
    name text not null,
    description text,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    settings jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index event_areas_event_code_unique_idx on public.event_areas (event_id, lower(code));

create table public.custom_field_templates (
    id bigint generated by default as identity primary key,
    event_id bigint not null references public.events(id) on delete cascade,
    legacy_id bigint,
    key text not null,
    label text not null,
    help_text text,
    field_type public.custom_field_kind not null,
    target_surface public.custom_field_target not null default 'registration',
    placeholder text,
    default_value jsonb,
    options jsonb not null default '[]'::jsonb,
    validation_rules jsonb not null default '{}'::jsonb,
    display_rules jsonb not null default '{}'::jsonb,
    sort_order integer not null default 0,
    is_required boolean not null default false,
    is_active boolean not null default true,
    is_system boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index custom_field_templates_event_key_unique_idx on public.custom_field_templates (event_id, lower(key));
create index custom_field_templates_event_target_idx on public.custom_field_templates (event_id, target_surface, sort_order);

create table public.language_defines (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    company_id bigint references public.companies(id) on delete cascade,
    event_id bigint references public.events(id) on delete cascade,
    locale text not null default 'vi',
    namespace text not null default 'default',
    key text not null,
    value text not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (company_id is not null or event_id is not null)
);

create unique index language_defines_scope_unique_idx
    on public.language_defines (
        coalesce(company_id, 0),
        coalesce(event_id, 0),
        lower(locale),
        lower(namespace),
        lower(key)
    );

create table public.media (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    company_id bigint references public.companies(id) on delete cascade,
    event_id bigint references public.events(id) on delete cascade,
    uploaded_by_user_id bigint references public.users(id) on delete set null,
    kind public.asset_kind not null default 'other',
    visibility public.asset_visibility not null default 'private',
    name text not null,
    alt_text text,
    storage_bucket text,
    storage_object_path text,
    public_url text,
    mime_type text,
    size_bytes bigint,
    width integer,
    height integer,
    duration_seconds integer,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index media_company_idx on public.media (company_id, visibility);
create index media_event_idx on public.media (event_id, visibility);

create table public.event_files (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    event_id bigint not null references public.events(id) on delete cascade,
    media_id bigint not null references public.media(id) on delete cascade,
    file_category text not null,
    title text,
    description text,
    sort_order integer not null default 0,
    is_public boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index event_files_event_category_idx on public.event_files (event_id, file_category, sort_order);

create table public.landing_pages (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid(),
    legacy_id bigint,
    event_id bigint not null references public.events(id) on delete cascade,
    slug text not null,
    name text not null,
    title text,
    status public.content_publication_status not null default 'draft',
    theme_key text,
    layout_version integer not null default 1,
    hero_content jsonb not null default '{}'::jsonb,
    blocks jsonb not null default '[]'::jsonb,
    form_settings jsonb not null default '{}'::jsonb,
    success_settings jsonb not null default '{}'::jsonb,
    seo_meta jsonb not null default '{}'::jsonb,
    published_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (public_id)
);

create unique index landing_pages_slug_unique_idx on public.landing_pages (lower(slug));
create index landing_pages_event_status_idx on public.landing_pages (event_id, status);

create table public.clients (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid(),
    legacy_id bigint,
    event_id bigint not null references public.events(id) on delete cascade,
    event_area_id bigint references public.event_areas(id) on delete set null,
    source public.client_source not null default 'manual',
    status public.client_status not null default 'pending',
    registration_code text,
    qr_code text,
    first_name text,
    last_name text,
    full_name text not null,
    email text,
    phone text,
    company_name text,
    title text,
    attendee_type text,
    ticket_type text,
    checked_in_at timestamptz,
    registration_payload jsonb not null default '{}'::jsonb,
    internal_notes text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (public_id)
);

create unique index clients_qr_code_unique_idx on public.clients (lower(qr_code)) where qr_code is not null;
create index clients_event_status_idx on public.clients (event_id, status, created_at desc);
create index clients_event_email_idx on public.clients (event_id, lower(email)) where email is not null;
create index clients_event_name_idx on public.clients (event_id, lower(full_name));

create table public.client_backups (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    event_id bigint not null references public.events(id) on delete cascade,
    source_media_id bigint references public.media(id) on delete set null,
    created_by_user_id bigint references public.users(id) on delete set null,
    backup_name text not null,
    backup_kind text not null default 'import',
    row_count integer not null default 0,
    snapshot_payload jsonb not null default '[]'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index client_backups_event_created_idx on public.client_backups (event_id, created_at desc);

create table public.client_custom_field_values (
    id bigint generated by default as identity primary key,
    client_id bigint not null references public.clients(id) on delete cascade,
    custom_field_template_id bigint not null references public.custom_field_templates(id) on delete cascade,
    value_jsonb jsonb not null default 'null'::jsonb,
    normalized_text text,
    normalized_number numeric(18, 4),
    normalized_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (client_id, custom_field_template_id)
);

create index client_custom_field_values_template_idx on public.client_custom_field_values (custom_field_template_id);

create table public.landing_page_submissions (
    id bigint generated by default as identity primary key,
    landing_page_id bigint not null references public.landing_pages(id) on delete cascade,
    event_id bigint not null references public.events(id) on delete cascade,
    client_id bigint references public.clients(id) on delete set null,
    submission_status public.landing_page_submission_status not null default 'submitted',
    submission_payload jsonb not null default '{}'::jsonb,
    utm_payload jsonb not null default '{}'::jsonb,
    submitted_at timestamptz not null default now(),
    confirmed_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index landing_page_submissions_page_idx on public.landing_page_submissions (landing_page_id, submitted_at desc);
create index landing_page_submissions_event_idx on public.landing_page_submissions (event_id, submission_status);

create table public.scanner_devices (
    id bigint generated by default as identity primary key,
    event_id bigint not null references public.events(id) on delete cascade,
    user_id bigint references public.users(id) on delete set null,
    device_name text not null,
    device_code uuid not null default gen_random_uuid(),
    status public.device_status not null default 'active',
    last_seen_at timestamptz,
    last_sync_at timestamptz,
    assigned_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (device_code)
);

create index scanner_devices_event_status_idx on public.scanner_devices (event_id, status);

create table public.scan_offline_batches (
    id bigint generated by default as identity primary key,
    scanner_device_id bigint not null references public.scanner_devices(id) on delete cascade,
    event_id bigint not null references public.events(id) on delete cascade,
    user_id bigint references public.users(id) on delete set null,
    status public.sync_batch_status not null default 'queued',
    row_count integer not null default 0,
    payload jsonb not null default '[]'::jsonb,
    synced_at timestamptz,
    error_message text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index scan_offline_batches_event_status_idx on public.scan_offline_batches (event_id, status, created_at desc);

create table public.checkins (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    event_id bigint not null references public.events(id) on delete cascade,
    client_id bigint not null references public.clients(id) on delete cascade,
    scanner_device_id bigint references public.scanner_devices(id) on delete set null,
    checked_by_user_id bigint references public.users(id) on delete set null,
    source_batch_id bigint references public.scan_offline_batches(id) on delete set null,
    event_area_id bigint references public.event_areas(id) on delete set null,
    status public.checkin_status not null default 'checked_in',
    method public.checkin_method not null default 'qr',
    happened_at timestamptz not null default now(),
    note text,
    payload jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index checkins_event_client_idx on public.checkins (event_id, client_id, happened_at desc);
create index checkins_event_happened_idx on public.checkins (event_id, happened_at desc);

create table public.reports (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    scope_type public.app_scope_type not null default 'event',
    company_id bigint references public.companies(id) on delete cascade,
    event_id bigint references public.events(id) on delete cascade,
    name text not null,
    key text not null,
    kind public.report_kind not null default 'table',
    description text,
    definition jsonb not null default '{}'::jsonb,
    default_filters jsonb not null default '{}'::jsonb,
    display_settings jsonb not null default '{}'::jsonb,
    cache_ttl_seconds integer not null default 0,
    is_system boolean not null default false,
    is_active boolean not null default true,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (
        scope_type <> 'self'
        and (
            (scope_type = 'system' and company_id is null and event_id is null)
            or (scope_type = 'company' and company_id is not null and event_id is null)
            or (scope_type = 'event' and company_id is not null and event_id is not null)
        )
    )
);

create unique index reports_scope_key_unique_idx
    on public.reports (
        scope_type,
        coalesce(company_id, 0),
        coalesce(event_id, 0),
        lower(key)
    );

create table public.report_runs (
    id bigint generated by default as identity primary key,
    report_id bigint not null references public.reports(id) on delete cascade,
    requested_by_user_id bigint references public.users(id) on delete set null,
    status public.report_run_status not null default 'queued',
    parameters jsonb not null default '{}'::jsonb,
    result_snapshot jsonb not null default '{}'::jsonb,
    row_count integer,
    started_at timestamptz,
    finished_at timestamptz,
    error_message text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index report_runs_report_status_idx on public.report_runs (report_id, status, created_at desc);

create table public.email_senders (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    company_id bigint not null references public.companies(id) on delete cascade,
    name text not null,
    from_name text not null,
    from_email text not null,
    reply_to_email text,
    provider public.integration_provider not null default 'postmark',
    provider_config jsonb not null default '{}'::jsonb,
    status public.email_sender_status not null default 'pending_verification',
    verified_at timestamptz,
    last_synced_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index email_senders_company_name_unique_idx on public.email_senders (company_id, lower(name));
create index email_senders_company_status_idx on public.email_senders (company_id, status);

create table public.email_templates (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    scope_type public.app_scope_type not null default 'company',
    company_id bigint references public.companies(id) on delete cascade,
    event_id bigint references public.events(id) on delete cascade,
    key text not null,
    name text not null,
    subject_template text,
    html_body text,
    text_body text,
    designer_state jsonb not null default '{}'::jsonb,
    sample_data jsonb not null default '{}'::jsonb,
    provider_template_id text,
    is_locked boolean not null default false,
    is_system boolean not null default false,
    status public.content_publication_status not null default 'draft',
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (
        scope_type <> 'self'
        and (
            (scope_type = 'system' and company_id is null and event_id is null)
            or (scope_type = 'company' and company_id is not null and event_id is null)
            or (scope_type = 'event' and company_id is not null and event_id is not null)
        )
    )
);

create unique index email_templates_scope_key_unique_idx
    on public.email_templates (
        scope_type,
        coalesce(company_id, 0),
        coalesce(event_id, 0),
        lower(key)
    );

create table public.email_template_unlock_requests (
    id bigint generated by default as identity primary key,
    email_template_id bigint not null references public.email_templates(id) on delete cascade,
    company_id bigint not null references public.companies(id) on delete cascade,
    requested_by_user_id bigint references public.users(id) on delete set null,
    reviewed_by_user_id bigint references public.users(id) on delete set null,
    status public.template_unlock_status not null default 'requested',
    reason text,
    reviewed_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index email_template_unlock_requests_status_idx on public.email_template_unlock_requests (company_id, status, created_at desc);

create table public.campaigns (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    event_id bigint not null references public.events(id) on delete cascade,
    email_sender_id bigint references public.email_senders(id) on delete set null,
    email_template_id bigint references public.email_templates(id) on delete set null,
    name text not null,
    subject text,
    preview_text text,
    status public.campaign_status not null default 'draft',
    audience_filter jsonb not null default '{}'::jsonb,
    audience_snapshot jsonb not null default '{}'::jsonb,
    scheduled_at timestamptz,
    started_at timestamptz,
    completed_at timestamptz,
    metrics jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index campaigns_event_status_idx on public.campaigns (event_id, status, created_at desc);

create table public.campaign_details (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    campaign_id bigint not null references public.campaigns(id) on delete cascade,
    client_id bigint references public.clients(id) on delete set null,
    recipient_email text not null,
    recipient_name text,
    status public.campaign_recipient_status not null default 'pending',
    provider_message_id text,
    sent_at timestamptz,
    delivered_at timestamptz,
    opened_at timestamptz,
    clicked_at timestamptz,
    bounced_at timestamptz,
    last_error_message text,
    merge_data jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index campaign_details_campaign_email_unique_idx on public.campaign_details (campaign_id, lower(recipient_email));
create index campaign_details_status_idx on public.campaign_details (campaign_id, status);

create table public.emails (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    campaign_id bigint references public.campaigns(id) on delete set null,
    campaign_detail_id bigint references public.campaign_details(id) on delete set null,
    client_id bigint references public.clients(id) on delete set null,
    sender_email text,
    recipient_email text not null,
    subject text,
    provider public.integration_provider not null default 'postmark',
    provider_message_id text,
    event_type text,
    occurred_at timestamptz not null default now(),
    payload jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index emails_campaign_idx on public.emails (campaign_id, occurred_at desc);
create index emails_provider_message_idx on public.emails (provider_message_id) where provider_message_id is not null;

create table public.labels (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    event_id bigint not null references public.events(id) on delete cascade,
    name text not null,
    slug text not null,
    status public.content_publication_status not null default 'draft',
    page_size text,
    orientation text not null default 'portrait' check (orientation in ('portrait', 'landscape')),
    canvas_config jsonb not null default '{}'::jsonb,
    default_data_mapping jsonb not null default '{}'::jsonb,
    printer_settings jsonb not null default '{}'::jsonb,
    is_default boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index labels_event_slug_unique_idx on public.labels (event_id, lower(slug));

create table public.label_details (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    label_id bigint not null references public.labels(id) on delete cascade,
    layer_key text not null,
    layer_type text not null,
    sort_order integer not null default 0,
    position jsonb not null default '{}'::jsonb,
    style jsonb not null default '{}'::jsonb,
    data_binding jsonb not null default '{}'::jsonb,
    conditions jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index label_details_label_sort_idx on public.label_details (label_id, sort_order);

create table public.cards (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    event_id bigint not null references public.events(id) on delete cascade,
    name text not null,
    slug text not null,
    status public.content_publication_status not null default 'draft',
    orientation text not null default 'portrait' check (orientation in ('portrait', 'landscape')),
    canvas_config jsonb not null default '{}'::jsonb,
    default_data_mapping jsonb not null default '{}'::jsonb,
    export_settings jsonb not null default '{}'::jsonb,
    is_default boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index cards_event_slug_unique_idx on public.cards (event_id, lower(slug));

create table public.card_details (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    card_id bigint not null references public.cards(id) on delete cascade,
    layer_key text not null,
    layer_type text not null,
    sort_order integer not null default 0,
    position jsonb not null default '{}'::jsonb,
    style jsonb not null default '{}'::jsonb,
    data_binding jsonb not null default '{}'::jsonb,
    conditions jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index card_details_card_sort_idx on public.card_details (card_id, sort_order);

create table public.printers (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    company_id bigint references public.companies(id) on delete cascade,
    event_id bigint references public.events(id) on delete cascade,
    name text not null,
    driver_key text,
    connection_settings jsonb not null default '{}'::jsonb,
    status public.printer_status not null default 'inactive',
    last_seen_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index printers_event_status_idx on public.printers (event_id, status);
create index printers_company_status_idx on public.printers (company_id, status);

create table public.print_jobs (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    company_id bigint references public.companies(id) on delete set null,
    event_id bigint references public.events(id) on delete cascade,
    printer_id bigint references public.printers(id) on delete set null,
    label_id bigint references public.labels(id) on delete set null,
    card_id bigint references public.cards(id) on delete set null,
    requested_by_user_id bigint references public.users(id) on delete set null,
    kind public.print_job_kind not null,
    status public.print_job_status not null default 'queued',
    requested_at timestamptz not null default now(),
    started_at timestamptz,
    finished_at timestamptz,
    copies integer not null default 1,
    input_payload jsonb not null default '{}'::jsonb,
    output_payload jsonb not null default '{}'::jsonb,
    error_message text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index print_jobs_event_status_idx on public.print_jobs (event_id, status, created_at desc);
create index print_jobs_printer_status_idx on public.print_jobs (printer_id, status, created_at desc);

create table public.print_job_items (
    id bigint generated by default as identity primary key,
    print_job_id bigint not null references public.print_jobs(id) on delete cascade,
    client_id bigint references public.clients(id) on delete set null,
    item_status public.print_item_status not null default 'queued',
    render_context jsonb not null default '{}'::jsonb,
    rendered_object_path text,
    printed_at timestamptz,
    error_message text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index print_job_items_job_status_idx on public.print_job_items (print_job_id, item_status);

create table public.audios (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    company_id bigint references public.companies(id) on delete cascade,
    event_id bigint references public.events(id) on delete cascade,
    name text not null,
    slug text,
    source_url text,
    storage_bucket text,
    storage_object_path text,
    duration_seconds integer,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index audios_scope_slug_unique_idx
    on public.audios (coalesce(company_id, 0), coalesce(event_id, 0), lower(slug))
    where slug is not null;

create table public.lucky_draws (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    event_id bigint not null references public.events(id) on delete cascade,
    audio_id bigint references public.audios(id) on delete set null,
    name text not null,
    status public.lucky_draw_status not null default 'draft',
    builder_state jsonb not null default '{}'::jsonb,
    runtime_settings jsonb not null default '{}'::jsonb,
    display_settings jsonb not null default '{}'::jsonb,
    audience_filter jsonb not null default '{}'::jsonb,
    started_at timestamptz,
    ended_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index lucky_draws_event_status_idx on public.lucky_draws (event_id, status, created_at desc);

create table public.lucky_draw_rewards (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    lucky_draw_id bigint not null references public.lucky_draws(id) on delete cascade,
    name text not null,
    description text,
    quantity integer not null default 1 check (quantity > 0),
    sort_order integer not null default 0,
    reward_value jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index lucky_draw_rewards_draw_sort_idx on public.lucky_draw_rewards (lucky_draw_id, sort_order);

create table public.lucky_draw_clients (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    lucky_draw_id bigint not null references public.lucky_draws(id) on delete cascade,
    client_id bigint not null references public.clients(id) on delete cascade,
    entry_status public.lucky_draw_entry_status not null default 'eligible',
    ticket_no text,
    eligibility_reason text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (lucky_draw_id, client_id)
);

create index lucky_draw_clients_status_idx on public.lucky_draw_clients (lucky_draw_id, entry_status);

create table public.lucky_draw_winners (
    id bigint generated by default as identity primary key,
    lucky_draw_id bigint not null references public.lucky_draws(id) on delete cascade,
    reward_id bigint references public.lucky_draw_rewards(id) on delete set null,
    client_id bigint not null references public.clients(id) on delete cascade,
    round_no integer not null default 1,
    selected_at timestamptz not null default now(),
    confirmed_at timestamptz,
    draw_payload jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index lucky_draw_winners_unique_idx on public.lucky_draw_winners (lucky_draw_id, coalesce(reward_id, 0), client_id);

create table public.n8n_chat_sessions (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid(),
    legacy_id bigint,
    company_id bigint references public.companies(id) on delete cascade,
    event_id bigint references public.events(id) on delete cascade,
    user_id bigint references public.users(id) on delete set null,
    client_id bigint references public.clients(id) on delete set null,
    title text,
    mode text not null default 'assistant',
    status public.chat_session_status not null default 'open',
    context_payload jsonb not null default '{}'::jsonb,
    last_message_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (public_id)
);

create index n8n_chat_sessions_scope_idx on public.n8n_chat_sessions (company_id, event_id, status);

create table public.n8n_chat_messages (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    session_id bigint not null references public.n8n_chat_sessions(id) on delete cascade,
    role public.chatbot_message_role not null,
    message_text text,
    tool_name text,
    tool_payload jsonb not null default '{}'::jsonb,
    token_usage jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index n8n_chat_messages_session_created_idx on public.n8n_chat_messages (session_id, created_at);

create table public.background_jobs (
    id bigint generated by default as identity primary key,
    company_id bigint references public.companies(id) on delete cascade,
    event_id bigint references public.events(id) on delete cascade,
    actor_user_id bigint references public.users(id) on delete set null,
    kind public.background_job_kind not null,
    status public.background_job_status not null default 'queued',
    idempotency_key text,
    payload jsonb not null default '{}'::jsonb,
    result_payload jsonb not null default '{}'::jsonb,
    attempts integer not null default 0,
    max_attempts integer not null default 3,
    scheduled_at timestamptz not null default now(),
    started_at timestamptz,
    finished_at timestamptz,
    error_message text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index background_jobs_idempotency_unique_idx on public.background_jobs (idempotency_key) where idempotency_key is not null;
create index background_jobs_status_idx on public.background_jobs (status, scheduled_at);
create index background_jobs_scope_idx on public.background_jobs (company_id, event_id, kind);

create table public.integration_logs (
    id bigint generated by default as identity primary key,
    company_id bigint references public.companies(id) on delete cascade,
    event_id bigint references public.events(id) on delete cascade,
    provider public.integration_provider not null,
    status public.integration_log_status not null default 'info',
    action text not null,
    request_payload jsonb not null default '{}'::jsonb,
    response_payload jsonb not null default '{}'::jsonb,
    error_message text,
    occurred_at timestamptz not null default now(),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index integration_logs_scope_idx on public.integration_logs (company_id, event_id, provider, occurred_at desc);

create table public.histories (
    id bigint generated by default as identity primary key,
    legacy_id bigint,
    company_id bigint references public.companies(id) on delete cascade,
    event_id bigint references public.events(id) on delete cascade,
    actor_user_id bigint references public.users(id) on delete set null,
    actor_type public.history_actor_type not null default 'user',
    action_key text not null,
    subject_table text,
    subject_id bigint,
    summary text,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index histories_scope_idx on public.histories (company_id, event_id, created_at desc);
create index histories_subject_idx on public.histories (subject_table, subject_id);

create table public.system_logs (
    id bigint generated by default as identity primary key,
    company_id bigint references public.companies(id) on delete cascade,
    event_id bigint references public.events(id) on delete cascade,
    user_id bigint references public.users(id) on delete set null,
    level public.system_log_level not null default 'info',
    source text,
    message text not null,
    context jsonb not null default '{}'::jsonb,
    occurred_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index system_logs_scope_idx on public.system_logs (company_id, event_id, occurred_at desc);
create index system_logs_level_idx on public.system_logs (level, occurred_at desc);

create table public.legal_documents (
    id bigint generated by default as identity primary key,
    document_key text not null,
    locale text not null default 'vi',
    title text not null,
    owner_name text not null default 'Giltech Solutions',
    content_html text,
    content_text text,
    version text not null,
    published_at timestamptz,
    is_active boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index legal_documents_unique_idx on public.legal_documents (lower(document_key), lower(locale), lower(version));

create table public.user_legal_acceptances (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    legal_document_id bigint not null references public.legal_documents(id) on delete cascade,
    accepted_at timestamptz not null default now(),
    ip_address inet,
    user_agent text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, legal_document_id)
);

create or replace function public.handle_auth_user_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.users (
        auth_user_id,
        email,
        full_name,
        display_name,
        status,
        login_app,
        metadata
    )
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
        coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'name'),
        'active',
        'web',
        coalesce(new.raw_user_meta_data, '{}'::jsonb)
    )
    on conflict (auth_user_id) do update
    set
        email = excluded.email,
        full_name = coalesce(excluded.full_name, public.users.full_name),
        display_name = coalesce(excluded.display_name, public.users.display_name),
        metadata = public.users.metadata || excluded.metadata,
        updated_at = now();

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_auth_user_created();

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'companies',
        'company_domains',
        'subscription_plans',
        'company_subscriptions',
        'users',
        'roles',
        'permissions',
        'events',
        'user_access_scopes',
        'event_settings',
        'event_areas',
        'custom_field_templates',
        'language_defines',
        'media',
        'event_files',
        'landing_pages',
        'clients',
        'client_backups',
        'client_custom_field_values',
        'landing_page_submissions',
        'scanner_devices',
        'scan_offline_batches',
        'checkins',
        'reports',
        'report_runs',
        'email_senders',
        'email_templates',
        'email_template_unlock_requests',
        'campaigns',
        'campaign_details',
        'emails',
        'labels',
        'label_details',
        'cards',
        'card_details',
        'printers',
        'print_jobs',
        'print_job_items',
        'audios',
        'lucky_draws',
        'lucky_draw_rewards',
        'lucky_draw_clients',
        'lucky_draw_winners',
        'n8n_chat_sessions',
        'n8n_chat_messages',
        'background_jobs',
        'integration_logs',
        'histories',
        'system_logs',
        'legal_documents',
        'user_legal_acceptances'
    ]
    loop
        execute format(
            'create trigger set_%1$s_updated_at before update on public.%1$s for each row execute function public.set_updated_at();',
            table_name
        );
    end loop;
end;
$$;

with permission_rows(permission_key, description) as (
    values
        ('company.view', 'View companies'),
        ('company.create', 'Create companies'),
        ('company.update', 'Update companies'),
        ('company.manage_settings', 'Manage company settings'),
        ('user.view', 'View users'),
        ('user.create', 'Create users'),
        ('user.update', 'Update users'),
        ('user.invite', 'Invite users'),
        ('user.approve_access', 'Approve access requests'),
        ('user.force_sign_out', 'Force sign out users'),
        ('user.assign_role', 'Assign RBAC roles'),
        ('role.view', 'View roles'),
        ('role.manage', 'Manage roles'),
        ('permission.view', 'View permissions'),
        ('event.view', 'View events'),
        ('event.create', 'Create events'),
        ('event.update', 'Update events'),
        ('event.clone', 'Clone events'),
        ('event.archive', 'Archive events'),
        ('event.feature.manage', 'Manage event feature flags'),
        ('event.media.manage', 'Manage event media'),
        ('event_settings.view', 'View event settings'),
        ('event_settings.update', 'Update event settings'),
        ('custom_field.view', 'View custom fields'),
        ('custom_field.manage', 'Manage custom fields'),
        ('custom_field.reorder', 'Reorder custom fields'),
        ('client.view', 'View clients'),
        ('client.create', 'Create clients'),
        ('client.update', 'Update clients'),
        ('client.delete', 'Delete clients'),
        ('client.import', 'Import clients'),
        ('client.export', 'Export clients'),
        ('client.generate_qr', 'Generate QR codes'),
        ('client.send_email', 'Send email to clients'),
        ('client.generate_card', 'Generate cards for clients'),
        ('checkin.view', 'View checkin logs'),
        ('checkin.run', 'Run checkin actions'),
        ('checkin.manage', 'Manage checkin runtime'),
        ('checkin.export', 'Export checkin logs'),
        ('checkin.reset', 'Reset checkin data'),
        ('report.view', 'View reports'),
        ('report.export', 'Export reports'),
        ('report.render', 'Render reports'),
        ('landing_page.view', 'View landing pages'),
        ('landing_page.create', 'Create landing pages'),
        ('landing_page.update', 'Update landing pages'),
        ('landing_page.clone', 'Clone landing pages'),
        ('landing_page.publish', 'Publish landing pages'),
        ('campaign.view', 'View campaigns'),
        ('campaign.create', 'Create campaigns'),
        ('campaign.update', 'Update campaigns'),
        ('campaign.clone', 'Clone campaigns'),
        ('campaign.cancel', 'Cancel campaigns'),
        ('campaign.send', 'Send campaigns'),
        ('email.view', 'View emails'),
        ('email.export', 'Export email delivery reports'),
        ('email.cancel', 'Cancel emails'),
        ('email.status.change', 'Change email statuses'),
        ('email_template.view', 'View email templates'),
        ('email_template.sync', 'Sync email templates'),
        ('email_template.update', 'Update email templates'),
        ('email_template.clone', 'Clone email templates'),
        ('email_template.unlock.manage', 'Manage email template unlocks'),
        ('email_template.unlock.request', 'Request email template unlocks'),
        ('email_sender.view', 'View email senders'),
        ('email_sender.manage', 'Manage email senders'),
        ('label.view', 'View labels'),
        ('label.create', 'Create labels'),
        ('label.update', 'Update labels'),
        ('label.clone', 'Clone labels'),
        ('label.print', 'Print labels'),
        ('label.render', 'Render labels'),
        ('card.view', 'View cards'),
        ('card.create', 'Create cards'),
        ('card.update', 'Update cards'),
        ('card.generate', 'Generate cards'),
        ('card.export', 'Export cards'),
        ('card.render', 'Render cards'),
        ('media.view', 'View media'),
        ('media.upload', 'Upload media'),
        ('media.delete', 'Delete media'),
        ('lucky_draw.view', 'View lucky draws'),
        ('lucky_draw.create', 'Create lucky draws'),
        ('lucky_draw.update', 'Update lucky draws'),
        ('lucky_draw.manage_rewards', 'Manage lucky draw rewards'),
        ('lucky_draw.run', 'Run lucky draws'),
        ('lucky_draw.reset', 'Reset lucky draw runtime'),
        ('lucky_draw.export_winners', 'Export lucky draw winners'),
        ('lucky_draw.builder.manage', 'Manage lucky draw builder'),
        ('audio.assign', 'Assign audio assets'),
        ('history.view', 'View histories'),
        ('system_log.view', 'View system logs'),
        ('chatbot.use', 'Use chatbot'),
        ('chatbot.mode.change', 'Change chatbot mode'),
        ('chatbot.history.view', 'View chatbot history'),
        ('chatbot.admin', 'Administer chatbot'),
        ('legal.view', 'View legal documents'),
        ('billing.view', 'View billing'),
        ('billing.manage', 'Manage billing')
)
insert into public.permissions (key, resource, action, description)
select
    permission_key,
    split_part(permission_key, '.', 1),
    substring(permission_key from position('.' in permission_key) + 1),
    description
from permission_rows;

insert into public.roles (key, name, description, default_scope, is_system_role)
values
    ('system_admin', 'System Admin', 'Cross-company administration', 'system', true),
    ('company_admin', 'Company Admin', 'Company administration role', 'company', false),
    ('event_manager', 'Event Manager', 'Event operations role', 'event', false),
    ('report_analyst', 'Report Analyst', 'Read-only analytics role', 'event', false),
    ('content_operator', 'Content Operator', 'Content and communications role', 'company', false),
    ('checkin_operator', 'Check-in Operator', 'Check-in runtime role', 'event', false),
    ('scanner_device', 'Scanner Device', 'Minimal scanner role', 'event', false),
    ('support_agent', 'Support Agent', 'Support and troubleshooting role', 'company', false);

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.key = 'system_admin';

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p
    on p.resource in (
        'company',
        'user',
        'event',
        'client',
        'checkin',
        'report',
        'landing_page',
        'campaign',
        'email_template',
        'label',
        'card',
        'lucky_draw',
        'media'
    )
    or p.key = 'chatbot.history.view'
where r.key = 'company_admin'
on conflict do nothing;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p
    on p.resource in ('client', 'checkin', 'report')
    or p.key in ('event.view', 'event.update', 'campaign.view', 'campaign.create', 'campaign.update')
where r.key = 'event_manager'
on conflict do nothing;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p
    on p.resource = 'report'
    or p.key in ('client.view', 'checkin.view', 'campaign.view')
where r.key = 'report_analyst'
on conflict do nothing;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p
    on p.resource in ('landing_page', 'campaign', 'label', 'card', 'media')
    or p.key = 'email_template.view'
where r.key = 'content_operator'
on conflict do nothing;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p
    on p.key in ('client.view', 'checkin.run', 'checkin.view', 'label.print', 'card.render')
where r.key = 'checkin_operator'
on conflict do nothing;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p
    on p.key in ('checkin.run', 'client.view')
where r.key = 'scanner_device'
on conflict do nothing;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p
    on p.key in ('history.view', 'system_log.view', 'chatbot.admin', 'chatbot.history.view', 'user.view')
where r.key = 'support_agent'
on conflict do nothing;
